[package]
name = "bob"
version = "0.1.0"
edition = "2024"

[dependencies]
confy = "2"
rquickjs = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = "2"

[build-dependencies]
tauri-build = "2"
